# Generated by Django 4.2.1 on 2023-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_picture', models.ImageField(upload_to='images_timetable')),
                ('call_schedule', models.ImageField(upload_to='images_call_schedule')),
            ],
        ),
    ]
