# Generated by Django 4.2.1 on 2023-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0002_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='call_schedule',
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_of_publication',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
