# Generated by Django 4.2.1 on 2023-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0003_remove_timetable_call_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сall_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_picture', models.ImageField(upload_to='images_call')),
                ('date_of_publication', models.DateTimeField()),
            ],
        ),
    ]
