# Generated by Django 4.2.1 on 2023-05-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0006_news_main_title_alter_news_main_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_main',
            options={'ordering': ('-date_public',), 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_school.news_main')),
            ],
        ),
    ]
