# Generated by Django 4.2.1 on 2023-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0007_alter_news_main_options_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сall_schedule',
            new_name='Call_schedule',
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('-date_of_publication',)},
        ),
    ]
