# Generated by Django 4.2.1 on 2023-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0008_rename_сall_schedule_call_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pride_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pride_school')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
    ]
