# Generated by Django 4.2.1 on 2023-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0009_pride_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call_schedule',
            options={'verbose_name_plural': 'Розклад дзвінків'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
        migrations.AlterModelOptions(
            name='pride_school',
            options={'verbose_name': 'Гордість школи', 'verbose_name_plural': 'Гордість школи'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Вчитель', 'verbose_name_plural': 'Вчителі'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Розклад уроків', 'verbose_name_plural': 'Розклади уроків'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
