# Generated by Django 4.2.1 on 2023-05-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0010_alter_call_schedule_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='slug',
        ),
    ]
