# Generated by Django 4.2.1 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_school', '0012_teacher_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='title',
            new_name='teacher_subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
